//! ALERT TYPES 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//! CONFIRM MODAL TYPES 
export const SET_MODAL = 'SET_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

//! AUTH TYPES
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAIL = 'USER_LOADING_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

//! POST TYPES
export const POST_ERROR = 'POST_ERROR';
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
export const FETCH_LIFESTYLE = 'FETCH_LIFESTYLE';
export const FETCH_LIFESTYLE_SUCCESS = 'FETCH_LIFESTYLE_SUCCESS';
export const FETCH_LIFESTYLE_FAIL = 'FETCH_LIFESTYLE_FAIL';
export const FETCH_DEVOTIONAL = 'FETCH_DEVOTIONAL';
export const FETCH_DEVOTIONAL_SUCCESS = 'FETCH_DEVOTIONAL_SUCCESS';
export const FETCH_DEVOTIONAL_FAIL = 'FETCH_DEVOTIONAL_FAIL';
export const FETCH_WELLNESS = 'FETCH_WELLNESS';
export const FETCH_WELLNESS_SUCCESS = 'FETCH_WELLNESS_SUCCESS';
export const FETCH_WELLNESS_FAIL = 'FETCH_WELLNESS_FAIL';
export const FETCH_GRAPHICS = 'FETCH_GRAPHICS';
export const FETCH_GRAPHICS_SUCCESS = 'FETCH_GRAPHICS_SUCCESS';
export const FETCH_GRAPHICS_FAIL = 'FETCH_GRAPHICS_FAILL';
export const FETCH_RECENT = 'FETCH_RECENT';
export const FETCH_RECENT_SUCCESS = 'FETCH_RECENT_SUCCESS';
export const FETCH_RECENT_FAIL = 'FETCH_RECENT_FAIL';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

//! SAVED POST TYPES
export const SAVE_ERROR = 'SAVE_ERROR';
export const SAVE_POST = 'SAVE_POST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL';
export const FETCH_SAVED = 'FETCH_SAVED';
export const FETCH_SAVED_SUCCESS = 'FETCH_SAVED_SUCCESS';
export const FETCH_SAVED_FAIL = 'FETCH_SAVED_FAIL';
export const DELETE_SAVED = 'DELETE_SAVED';
export const DELETE_SAVED_SUCCESS = 'DELETE_SAVED_SUCCESS';
export const DELETE_SAVED_FAIL = 'DELETE_SAVED_FAIL';
export const FETCH_SAVED_POST = 'FETCH_SAVED_POST';
export const FETCH_SAVED_POST_SUCCESS = 'FETCH_SAVED_POST_SUCCESS';
export const FETCH_SAVED_POST_FAIL = 'FETCH_SAVED_POST_FAIL';
export const RESAVE_POST = 'RESAVE_POST';
export const RESAVE_POST_SUCCESS = 'RESAVE_POST_SUCCESS';
export const RESAVE_POST_FAIL = 'RESAVE_POST_FAIL';
// this one is for removing from the saved reducer
export const PUBLISH_SAVED_POST_REMOVE = 'PUBLISH_SAVED_POST_REMOVE';
export const PUBLISH_SAVED_POST_REMOVE_SUCCESS = 'PUBLISH_SAVED_POST_REMOVE_SUCCESS';
export const PUBLISH_SAVED_POST_REMOVE_FAIL = 'PUBLISH_SAVED_POST_REMOVE_FAIL';
// this one is for adding to the post reducer
export const PUBLISH_SAVED_POST_ADD = 'PUBLISH_SAVED_POST_ADD';
export const PUBLISH_SAVED_POST_ADD_SUCCESS = 'PUBLISH_SAVED_POST_ADD_SUCCESS';
export const PUBLISH_SAVED_POST_ADD_FAIL = 'PUBLISH_SAVED_POST_ADD_FAIL';

//! FOOTER
export const RENDER_FOOTER = 'RENDER_FOOTER';
export const HIDE_FOOTER = 'HIDE_FOOTER';